version: '3'
services:
  www:
    image: wasserball/docker-static-html-with-basic-auth
    ports:
      - '80:80'
    environment:
      - DEBUG=1
      - HTPASSWD='root:$$1$$qoTrIqHu$$JNSTlAb2ujbqDumGaKTpL0'
    volumes:
      #- ".htpasswd:/etc/nginx/.htpasswd" # can be used to replace the PW if you are not using the environment var
      - "./build:/usr/share/nginx/www"
