version: '3'
services:
  www:
    #image: wasserball/docker-static-html-with-basic-auth
    build: .
    ports:
      - '80:80'
    environment:
      - HTPASSWD=root:$$1$$iGoV]ccv$$al2Yxql/iYA85YSwsjDYm0
    volumes:
      #- ".htpasswd:/etc/nginx/.htpasswd" # can be used to replace the PW if you are not using the environment var
      - "./build:/usr/share/nginx/www"
